//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.23 at 10:21:45 AM EET 
//


package targetclasses;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for VisualParameters complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VisualParameters"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="stalkColor" type="{targetClasses}StalkColor"/&gt;
 *         &lt;element name="leavesColor" type="{targetClasses}LeavesColor"/&gt;
 *         &lt;element name="averageSize" type="{targetClasses}FlowerSize"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VisualParameters", propOrder = {
    "stalkColor",
    "leavesColor",
    "averageSize"
})
public class VisualParameters {

    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected StalkColor stalkColor;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected LeavesColor leavesColor;
    @XmlSchemaType(name = "integer")
    protected int averageSize;

    /**
     * Gets the value of the stalkColor property.
     * 
     * @return
     *     possible object is
     *     {@link StalkColor }
     *     
     */
    public StalkColor getStalkColor() {
        return stalkColor;
    }

    /**
     * Sets the value of the stalkColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link StalkColor }
     *     
     */
    public void setStalkColor(StalkColor value) {
        this.stalkColor = value;
    }

    /**
     * Gets the value of the leavesColor property.
     * 
     * @return
     *     possible object is
     *     {@link LeavesColor }
     *     
     */
    public LeavesColor getLeavesColor() {
        return leavesColor;
    }

    /**
     * Sets the value of the leavesColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link LeavesColor }
     *     
     */
    public void setLeavesColor(LeavesColor value) {
        this.leavesColor = value;
    }

    /**
     * Gets the value of the averageSize property.
     * 
     */
    public int getAverageSize() {
        return averageSize;
    }

    /**
     * Sets the value of the averageSize property.
     * 
     */
    public void setAverageSize(int value) {
        this.averageSize = value;
    }

}
